FROM ubuntu:20.04
ADD . /
WORKDIR /analytics_orchestrator/analytics_orchestrator_src/adapters/azure_function/fcn
RUN apt-get update && apt-get install -y curl gpg-agent
RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg &&\
    mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg &&\
    sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-bionic-prod bionic main" > /etc/apt/sources.list.d/dotnetdev.list'
RUN apt-get update && apt-get install -y python3.8 \
                        python3-dev \
                        python3-pip \
                        gcc \
                        libc-dev \
                        libffi-dev \
                        g++ \
                        azure-functions-core-tools-3
RUN pip3 install --no-cache --upgrade pip setuptools
COPY ./analytics_orchestrator/analytics_orchestrator_src/adapters/azure_function/fcn/requirements.txt /analytics_orchestrator/analytics_orchestrator_src/adapters/azure_function/fcn
RUN pip3 install --upgrade pip && \
    pip3 install wheel &&\
    pip3 install --default-timeout=100 -r requirements.txt
RUN export BLOB_STORAGE_CONTAINER_NAME="ai-pipeline"
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
RUN export BLOB_STORAGE_CONNECTION_STRING="DefaultEndpointsProtocol=https;AccountName=aipipelinecore;AccountKey=zTX01P5Y1NXzCZj+GzmRE+lgPU6mEzJNozx0qkn0nDLm8jv9SPPb4ZcubikTJD4M64JXsbu3GA3iwyKohO+8Hw==;EndpointSuffix=core.windows.net"
CMD ["func", "start"]






