FROM python:3.7.0-alpine
ADD . /
WORKDIR /endpoint
RUN apk update && apk add python3-dev \
                        gcc \
                        libc-dev
RUN pip3 install --no-cache --upgrade pip setuptools
ADD ./endpoint/requirements.txt /endpoint
RUN pip3 install --upgrade pip && \
    pip3 install wheel &&\ 
    pip3 install --default-timeout=100 -r requirements.txt
EXPOSE 3000
CMD ["python", "./endpoint_src/routes/app.py"]

