FROM python:3.7.13-alpine3.15
ADD . /
WORKDIR /analytics_orchestrator
RUN apk update && apk add python3-dev \
                        gcc \
                        libc-dev \
			libffi-dev \
			g++
RUN pip3 install --no-cache --upgrade pip setuptools
ADD ./analytics_orchestrator/requirements.txt /analytics_orchestrator
RUN pip3 install --upgrade pip && \
    pip3 install wheel &&\ 
    pip3 install --default-timeout=100 -r requirements.txt
EXPOSE 3004
CMD ["python", "./analytics_orchestrator_src/routes/app.py"]

